CREATE DATABASE "Vehicle_Market_Value_API";

\c "Vehicle_Market_Value_API"


CREATE TABLE roles
(
    role_id bigint generated by default as identity,
    role_type character varying not null,

    constraint roles_pkey primary key (role_id)
);

INSERT INTO roles
    (role_id, role_type) 
VALUES 
    (1, 
    'super admin'),

    (2, 
    'admin'),

    (3, 
    'employee') 
;



CREATE TABLE users
(
    user_id uuid not null default gen_random_uuid (),
    email character varying not null,
    first_name character varying not null,
    last_name character varying not null,
    password character varying not null,
    role bigint not null,
    working_status boolean not null,
    created_at timestamp with time zone not null default now(),

    constraint users_pkey1 primary key (email),
    constraint users_user_id_key unique (user_id),
    constraint public_users_role_fkey foreign key (role) references roles (role_id)
);

INSERT INTO users
    (email, first_name, last_name, password, role, working_status) 
VALUES 
    ('oscar@epongassociates.com.my', 
    'ocsar',
    'chang', 
    '244abe2db96c12feeb43fb18dcb016c166bdf367f8c61c8bc3dd2be47ec768ea',
    1,
    TRUE),
    
    ('lingges@epongassociates.com.my', 
    'lingges',
    'arulsamy', 
    '488f1117e6d9de5901440081523a4c82380d69f53f503c8a8c9c20ee0fca434c',
    1,
    TRUE)
;

CREATE TABLE vehicles
(
    id uuid not null default gen_random_uuid (),

    vehicle_type character varying not null,
    vehicle_make character varying not null,
    vehicle_model character varying not null,

    vehicle_reg_num character varying not null,
    vehicle_engine_cc bigint not null,
    vehicle_engine_num character varying not null,
    vehicle_chassis_num character varying not null,

    vehicle_body_type character varying not null,

    vehicle_manufacture_year bigint not null,

    vehicle_origin_type character varying not null,

    vehicle_min_market_value bigint null,
    vehicle_max_market_value bigint null,

    created_by uuid not null,
    created_at timestamp with time zone not null default now(),
    
    edited_by uuid null,
    edited_at timestamp with time zone null default now(),

    constraint vehicles_pkey1 primary key (id),
    constraint public_vehicles_created_by_fkey foreign key (created_by) references users (user_id),
    constraint public_vehicles_edited_by_fkey foreign key (edited_by) references users (user_id)
);

